apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/dgoeke/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - dgoeke/argo-combined-app:f688792946613cc1e63b0a0e9f78df50b86a3f6b
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

