apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nextcloud
  labels:
    component: app
  name: app
spec:
  selector:
    matchLabels:
      component: app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - image: nextcloud:21-apache
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: db-secrets
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: db-secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: db-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db-secrets
          volumeMounts:
            - mountPath: /var/www/html
              name: app-persistent-storage
      restartPolicy: Always
      volumes:
        - name: app-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: nextcloud
  labels:
    component: app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    component: app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: nextcloud
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - cloud.dgoeke.io
    secretName: nextcloud-tls
  rules:
    - host: cloud.dgoeke.io
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cron
  name: cron
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: cron
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - image: nextcloud:21-apache
          name: cron
          command:
            - /cron.sh
          volumeMounts:
            - name: app-persistent-storage
              mountPath: /var/www/html
      restartPolicy: Always
      volumes:
        - name: app-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc