apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nextcloud
spec:
  template:
    spec:
      containers:
        - image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nextcloud
spec:
  ports:
    - port: 6379