apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA1O7BJxblFYcsgeJRk7oU/pz/FFYnTK4rLHdfPUj6dipCYsFEYQjEHxGpsA+ALHnH9SpC/ZrrOrB38foDUKbsCCUo+66bTB6Ek/eLlNXqLK+jc9DfAM4xoCwMkeQlP/4+K9jgl3tJW7EKZ6GzMVwLAfC5qAkxpFd2cC6iHqRzJTNM4ESWG1Y/7X2ymwX3iFklJGoEXZWpsIrbxVkL3SLoNiMazb/hv5q4CqkX8sYVAp+f3CYaibo3oBvFOPByWcLS1ZqgPzbGsDPHLFVV7RyouNpiV30LHP8BrIxHQ35mo0krW5mCYz7nLDUJgAOklGJClwuBjT3FrCrZM02bkow8pT9QwRGVscqKr4uSX12DJ4nciup43jc34+Zn3ENJsHdXrpBqEBkDkH5YnlgFTgyp/Ez5Q43SNkj8K2fI3SuMBQ2tP57nriQzYlP9teHpBgNRfOe/z/fXilu5/UiotrD/z1rDLzaiciUiQXurUMV4it0AkIG5SVvZBRGL5/lN//8YGt0cXAEvNxku7AxgkudpwavuX8rJz663BRv95IYHw1cvEL/rLJcWFojM+89yUydZd8mayDwo+C23hhudyYrWQUR6I+VJgUnCjg+H6kZO9twgCxG3E8nxTakGwsvji+TGOhR5Os2QQMaowguvSHTsNd1ps0OI8TlnCpkKSwf1FRooZsZpLG+33erHYzlYX1SE=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

