apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCryqW9nSct1HiS4U3Y/XAiE9iBHQ1uIc6oh2rvLs6s1JHRcf1AZGbYarJoWbj/fYeugBvaykl48KXRdeYqF47WEomd6RHoE9rEVIPiqsAKziNGbDkTgWG5NWrNxL0QhO2lloymZyiLUjPqL3ana2ssM4lfhJv5R7cWb4qtw1xi9fF3GHn4NhFZJ+U+a/cG9YeIQh5wr1KKLBB+g0OIlTdFfLjOdU7/xbPHx19DDI0AsgW7XS2xXeNGoyZhhslfyqby49atdUVbsVK6ct6DDsW+Wqa3vCtcFoYhgqpx+3YN/Yr7Iqj1sdTirPe1fhEWWPpMiJnRN81DOjmW+43+pe8ufrpAD/uitZNmFl02NHGkodzFXCxbILy2YBM7H4WPENV7O15xpPsVryIpRly2bkyRVCiMo8MM0qjNtpJp3BE7Djox1Zl6R6sq7JUCBexVVLqGQf2dq5wYFHF34f3Bm+clyHP49Lks1UuwGyBp1NVjw+VP8jQRt5cYn4Hc+LqRUtxqY765v10kpjebo+KKDKyvZXDrjdq+j+Z6SMIHCRBc0W0Fm8Cm0sxCd9TUy3xeLm6Qqfrfp09o57CofJb0MbKWY85N3Glf9K+xvwxxYUrTNVpUMK9jpK+u83ZfjEnxNHnyZB9k4dv+4pHBt01VuBOt3yRuaIp+q+RsBkQT+2+jCFIBBZwq+KsO/kcjznHUUyBKy9bJSAey2m0WQIozecN4XDav0112FgAY2nkpzXBjPXBoh/X/Ket1
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

